job:
  name: tokenizer_building_experiment

data:

  data_folder: /capstor/store/cscs/swissai/a131/ML4Science/datasets/CEMB_v1tags_HF_FineWeb-chemV1
  data_files_pattern: "**/*.arrow" 
  text_field: text_annotated_v1tags
  count_field: text_annotated_v1tags_smiles_count
  portion_of_data: 1.0

tokenizer:
  type: hybrid
  chem_type: ape_hf
  output_dir: /users/$USER/json/tokenizers
  output_subdir_name: ape_hf_20000
  params:
    max_vocab_size: 20000
    min_freq_for_merge: 2
