job:
  name: tokenizer_building_experiment

data:

  data_folder: /capstor/store/cscs/swissai/a131/ML4Science/datasets/CEMB_v1tags_HF_FineWeb-chemV1
  data_files_pattern: "**/*.arrow" 
  text_field: text_annotated_v1tags
  count_field: text_annotated_v1tags_smiles_count

tokenizer:
  type: hybrid
  chem_type: smiles_wp
  output_dir: /users/mattiaferrarini/smiles-mid-training/json/tokenizers
  params:
    max_vocab_size: 20000 
    min_freq_for_merge: 2