job:
  name: gemma_chem_training

model:
  name: google/gemma-3-1b-pt

data:
  data_folder: /capstor/store/cscs/swissai/a131/ML4Science/datasets/CEMB_v1tags_HF_FineWeb-chemV1
  data_files_pattern: "**/*.arrow"
  text_field: "text_annotated_v1tags"
  portion_of_data_used: 0.5 # Portion of the main dataset to use

data_mix:
  external_dataset_name: HuggingFaceFW/fineweb-edu
  external_subset_name: sample/100BT # Specify subset if needed
  files_per_main_index: 10
  external_data_files: [] # Empty if we want to stream the whole dataset
  probabilities: [0.2, 0.8] # Sampling ratio between main dataset and FineWeb

distributed:
  strategy: "ddp" # Options: "ddp" or "fsdp"
  ddp:
    find_unused_parameters: false
    backend: "nccl"
  fsdp:
    policy: "full_shard auto_wrap" 
    config:
      fsdp_transformer_layer_cls_to_wrap: "Gemma3DecoderLayer"

training:
  epochs: 1 
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-4
  max_steps: 20000 #50000
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  weight_decay: 0.05
  save_steps: 400
  logging_steps: 100
  resource_logging_steps: 100
  bf16: true
  fp16: false
  evaluation_strategy: "no"
  save_strategy: "steps"
  seed: 42
  gradient_checkpointing: true
  num_workers: 4
  preprocessing_num_workers: 64
  preprocessing_batch_size: 100
  prefetch_factor: 4
  per_device_batch_size: 4
  max_length: 4096
  stride_size: 1024
  report_to: "wandb"

tokenizer:
  type: hybrid
  chem_type: "ape_wp_hf"
  output_dir: "/users/mattiaferrarini/smiles-mid-training/json/tokenizers"
  output_subdir_name: "ape_wp_hf_20000"
  embedding_initialization: "random" 
  special_tokens:
    start_smiles: "[START_SMILES]"
    end_smiles: "[END_SMILES]"
