

model:
  name: "HuggingFaceTB/SmolLM2-135M-Instruct"


data:

  data_folder: "trl-lib/Capybara" 

training:
  output_dir: "./results"
  
  epochs: 3             
  batch_size: 4         
  gradient_accumulation_steps: 4
  # just to test it
  max_steps: 5
  learning_rate: 1.0e-5  # usually lower for Instruction Tuning
  warmup_steps: 50
  save_steps: 500
  logging_steps: 25
  bf16: true
  fp16: false
  seed: 42

# in order to change less parameters during fine-tuning
peft:
  use_lora: true 
  lora_r: 16             # 8, 16, 32 are common values.
  lora_alpha: 32         # Alpha: Usually double the rank or equal.
  lora_dropout: 0.05
  lora_target_modules: 
    - q_proj
    - k_proj
    - v_proj