job:
  name: tokenizer_building_kmer

data:
  data_folder: /capstor/store/cscs/swissai/a131/ML4Science/datasets/CEMB_v1tags_HF_FineWeb-chemV1
  text_field: text_annotated_v1tags

tokenizer:
  type: kmer
  output_dir: /iopsstor/scratch/cscs/monti/tokenizers_saved
  params:
    ngram: 4
    stride: 1
    max_vocab_size: 50000